// Generated by ~/.config/tinty/hooks/apply.sh from tinty scheme: base16-catppuccin-macchiato
export const variables = {
  main: "#24273a",
  mainAlt: "#1e2030",
  minor: "#363a4f",
  accent: "#eed49f",
  red: "#ed8796",
  green: "#a6da95",
  yellow: "#eed49f",
  orange: "#f5a97f",
  blue: "#8aadf4",
  magenta: "#c6a0f6",
  cyan: "#8bd5ca",
};
